### ISSUE TITLE
Source code missing?

### ISSUE THREAD

**Issue by rmse17** [Superfly-Inc/ShowKeyPlus#1]
Hey, I am trying to download the source code, but in the source code files there is just a license.  Where is the actual source?

**Comment by cleberzavadniak** [comment]
Is it really "GPLed"? Where are the sources?

**Comment by Superfly-Inc** [comment]
GPL does not mean open source - it's freeware only. It's not obfuscated though. So reflect it if you need to... just do not fork the source.

**Comment by cleberzavadniak** [comment]
Man, please, read the license you included in your own project to avoid such misunderstandings:
https://github.com/Superfly-Inc/ShowKeyPlus/blob/master/LICENSE

**Comment by Superfly-Inc** [comment]
I have no control what GitHub adds in terms of licencing... Some of the source is from a bunch of others that I have not had explicit permission to publish - I'm using it as proxy. Please respect that.

**Comment by adlermedrado** [comment]
@Superfly-Inc It's not GPL. What about change your "License"?

**Comment by joecare99** [comment]
@Superfly-Inc: The meaning of open-source ist that the source is open, You choose the Open-Source Licence (GPL), otherwise you have to choose another licence !

**Comment by Superfly-Inc** [comment]
Licence changed - hope everybody is happy now, 

This was never a collaborative project, so a non-issue.
