### ISSUE TITLE
Non silent when no Windows installation found

### ISSUE THREAD

**Issue by Svoffer** [Superfly-Inc/ShowKeyPlus#10]
I'm trying to implement ShowKeyPlus in an Windows installation via SCCM and running it under Windows PE.
It is outputting to the txt file just find, but it is showing the GUI with the message:
"Auto-discovery did not find any Windows installations"
"OEM information found..."

Can you make it so it doesn't show the GUI in this case?

Svoffer

**Comment by Superfly-Inc** [comment]
I wouldn't want to suppress the GUI globally when there are no Windows installations as some may want to know that there is an OEM key,,, however if  you want silent, you can use it in CLI mode. If that does not work for you give me  a spec with the typical scenarios you encounter.

**Comment by Svoffer** [comment]
I am using the CLI mode. Outputting to a txt file.
When running the CLI mode on an installed Windows it shows nothing, but under Windows PE(Windows Setup), there is no installed OS and thereby no keys. It is here that I see the GUI. But it does make the txt file.

**Comment by Superfly-Inc** [comment]
Oh I see...CLI should not display that - is the txt file complete though? i.e should it say no windows installations.

**Comment by Svoffer** [comment]
The txt file is just right, thanks. 
It also gives the OEM info. Though I think I only remember the output on a machine with a Windows 7 maker. I'll check one with a Windows 10 key tomorrow.

**Comment by Svoffer** [comment]
Yes, txt file is complete with Windows 10 OEM information.

**Comment by Superfly-Inc** [comment]
@Svoffer and anyone else. 

Please test that this is fixed in version 6230.

**Comment by Svoffer** [comment]
Superfly, I can confirm that this is fixed.
Many thanks. =)

**Comment by Superfly-Inc** [comment]
You're welcome

Thanx for your support.
