### ISSUE TITLE
Same key all over

### ISSUE THREAD

**Issue by oywino** [Superfly-Inc/ShowKeyPlus#11]
Showkey v1.0.6371  shows the same key on all my Windows 10 Pro computers!
Of course this is not the case, and I know that each computer has been installed with a unique key.
The only possible explanation I can think of, is the fact that I chose to store the ShowKey EXE file on a NAS server, and I run the same exe files from all my computers.
Could that be the reason?

**Comment by StarMariner** [comment]
WINDOWS 10 COA are the same?
Default Windows 10 Home product key: YTMG3-N6DKC-DKB77-7M9GH-8HVX7
Default Windows 10 Pro product key:      VK7JG-NPHTM-C97JM-9MPGT-3V66T

If you see those product keys above, that's the same for every Windows 10 PC in the world that was upgraded during the Microsoft offer. If there is a way finding the Windows 7 , that would be the Product key to use when re-installing windows 10. 

Additional: However, I beleive you would need to have a internet link and Microsoft account as the computers will be linked to the account are digitally stored on there servers.  Nowday's not standalone product keys.

**Comment by oywino** [comment]
Thank you very much for the answer, and Yes - it is the key ending on 3V66T
The Windows 7 key is found on the Microsoft label on every Laptop I have, but most of them are OEM keys and I could not use that key successfully during upgrade to Windows 10 after the free upgrade period had expired.
So I bought new Windows licenses for the notebooks and they were activated with the new license keys after clean installation of Windows 10 Pro. Still only the 3V66T key shows up using "ShowKey".

**Comment by Superfly-Inc** [comment]
If you purchase Windows 10 via Store, you will get a digital licence which uses the generic key you have (like using the Windows 7 key) 

If you did use retail Windows 10 keys and clean installed subsequently electing not to enter a key, it will get the digital licence from the previous key install.

**Comment by oywino** [comment]
Thanks for your support @Superfly-Inc, but I find this difficult to understand. The reason I wish to use **ShowKey** is because I bought 4 new Win 10 Pro Licenses at once and installed 4 machines using them. However - I made one big mistake; I never noted which license I used with which machine.
What is the difference between a Retail key and a digital Store Key (as you call it) ?
I never elected not to enter a Key (as far as i recall)...

However, I clean installed Win 10 today on a PC which previously had Windows 7 Enterprise on it - and I had prepared myself with a new key (bought from the store), but curiously enough, the installation program never asked for the key. And after successful installation, Windows 10 Pro came up activated (I never did that), and when I ran **ShowKey** it came back with the 3V66T key again... ??  Beats me!  It feels like I wasted my money.

**Comment by StarMariner** [comment]
oywino , here a little work around that may help, not to do with showkey though. If you created a Microsoft account for windows 10 and used the same account on all machines, login to the https://account.microsoft.com/account . On the main page you will see devices. That might help in identifying what licence went with what machine. I guess you might be like me and have a laptop, desktop , may be 4G on one 8G on the other, intel , AMD etc.

**Comment by oywino** [comment]
Again, thanks for answering. I did (and have done before) log on to my account at MS. All devices are listed, but there is no info anywhere as to the Key used. They are all Win 10 Pro (That's what I use).

**Comment by Superfly-Inc** [comment]
I, unfortunately do not have first-hand experience with the store "keys". From what I gather they are 1-time activation keys to get digital licences - I assume therefore,  they (as in upgrade Windows 7 and Windows 8 keys are not retained after they get digital activation and only the generic key is thus available) but I could be wrong, others that have purchased store licences may be of more help.

**Comment by r31urn** [comment]
@Superfly-Inc   @oywino 
* Windows 10 Activation works this way 
--> If you have upgraded from Windows 7/8.1 to 10 --> **Digital licence** based on  hardware ID, And the previous product key. (Previous version product key can be used to activate windows 10 but was feature was removed  after Jan 2017).
--> If you have a **OEM product key**  5x5 code includes **oem dm/ coa non spl/dwgrd** , uses the product key + digital licence based on the hardware ID.
--> If you purchase a Windows 10 product key from retail store (Physical copy of the product key or DPK)  5x5 code, uses the product key + digital licence based on the hardware ID.
--> If you buy it directly from the store, then the license is linked to your MSA (Microsoft account) and your hardware ID.

In all the cases the licenses can be linked to your MSA 
**There is no Product key in the store purchase as a digital license (Nothing as such as its stored on sever  as a 5x5 or can be retrieved to a 5x5 code) .**

The devices listed on you Microsoft account really does tell about the activation but only the devices logged with the account. 
 
Also people who purchase keys from online website for really cheap (OEM keys) Most don't activate after reinstall as the sellers sell it multiple people, so reactivating depends on you MSA.

Note some keys sold online are MSDN keys unless you upgrade from older version you cannot link it to your account.


Any questions or thoughts, or any mistakes please let me know!!

**Comment by oywino** [comment]
Ohoo...   "oem dm/ coa non spl/dwgrd"  -  ?!?

**Comment by r31urn** [comment]
@oywino  OEM DM -->
/ Original equipment Manufacturer Digital marker 
/ OEM Certificate of Authenticity 
/ OEM COA NON System pre-locked 
/ OEM Downgrade Rights.

First one is where only a Window 10 sticker on the computer (Product key is digitally injected in the computer  (WMIC command will retrieve the key or the showkeyplus :p)
Second is where a Windows product key is printed on the a sticker and usually stuck to  the tower , you 90% of the time will have to enter the product key to activate (System builder will do this most often like CyberPC UK or NCIX in US,, etc).
Third is the same , OEM SPL is disconnected except the in rare sever scenarios  so its always (NON SPL)
Forth being when you order a computer with Windows 10 Home and you want to upgarde you add a Windows 10 pro during a purchase then you will get a machine with a Windows 10 Home and sticker of the Windows 10 Pro key, you will to enter the key to upgrade.

Hope this clears everything :)

**Comment by oywino** [comment]
:) Thanks.
