### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by pschneider1989** [Superfly-Inc/ShowKeyPlus#13]
Hi,

I saw in your release notes:
Suppress messagebox when in CLI mode.

How can I enter CLI mode?

Thanks in advance,
Patrick

**Comment by Superfly-Inc** [comment]
Hi Patrick

To use CLI to generate a text file of installed, original and OEM key(s) and their editions, silently.

Usage:
"[path]\ShowKeyPlus.exe" "[path][filename].txt"
 (or any text compatible extension, eg: .doc, .csv etc)

Note the space between the exe and args[]

HTH

**Comment by pschneider1989** [comment]
I created a Batch as a logon script to store .TXT file in a central path.
Works great- thank you so much!

@ECHO OFF
\\...\ShowkeyPlus\ShowKeyPlus.exe \\...\ShowKeyPlusLicenses\LIC_%COMPUTERNAME%.TXT

**Comment by Superfly-Inc** [comment]
You are welcome, Good to hear.

All the best.
