### ISSUE TITLE
Add: 'Certificate installation' extra steps

### ISSUE THREAD

**Issue by rain2reign** [Superfly-Inc/ShowKeyPlus#14]
Add additional instructions for those whom can't get the certificate installed and/or get the certification error and thus fail the installation. You need to manually select a certificate folder. 

Here are the following steps:
- Right-click "ShowKeyPlusUWP_1.1.2.0_AnyCPY.appxbundle" and click on properties.
- Click on the tab named 'Digital Signatures'.
- Double-click the (single) signature you see in that tab.
- Click on 'View Signature'.
- Click on the button with the name "Install signature", "Install Certificate" or something of that nature      (my OS is in Dutch, i apologize for this).
- Select 'local machine' and click next.
- Select 'place all certificates in the following store'.
- Click browse and select 'Trusted Root certification authorities'.
- Click next and click on finish.

Now you should be able to install/use the ShowKeyPlus UWP application. I hope this may prove useful for those whom need it. :)

**Comment by Superfly-Inc** [comment]
@rain2reign

Many thanx for clarifying the procedure.

It should be installed to Local Machine.
