### ISSUE TITLE
Windows XP support broken?

### ISSUE THREAD

**Issue by kleinerkaserer** [Superfly-Inc/ShowKeyPlus#15]
Version 1.0.5835 runs fine on Windows XP if .NET Framework 4 is installed.
However, the latest Version 1.0.6594 stops immediately after starting without producing any visible output or error message

**Comment by Superfly-Inc** [comment]
XP has never been supported 'officially' - I'm pleasantly surprised 5835 works on it :) 

There has been a lot of additions between that build and now, any of which could have broken XP functioning.
Version 1.0.5835 build will always be available for backward compatibility and those wanting bare-bones.

Thanx for your feedback.

**Comment by kleinerkaserer** [comment]
Am 2018-02-08 11:35, schrieb Craig - Superfly:
> XP has never been supported 'officially' - I'm pleasantly surprised
> 5835 works on it :)
> 
> There has been a lot of additions between that build and now, any of
> which could have broken XP functioning.
> Version 1.0.5835 build will always be available for backward
> compatibility and those wanting bare-bones.
> 
> Thanx for your feedback.

Hello Craig,

thank you for your fast response.
However, I would like to tell you that description for Version 1.0.5835 
on github contains the following text:

Update to Version 1.0.5730.
  Automated discovery of pre-existing Windows installations (from Windows 
and Windows.old folders) that are in their default locations (root 
drives). It supports Windows XP through Windows 10 key retrieval.

I spent several hours in investigating the issue of how to make the 
Software run under XP!
Maybe you could clarify the description?

Thank you very much!

Ralf Wehrmann
Technical University Munich
Department for Radiation Therapy

**Comment by Superfly-Inc** [comment]
Hello Ralf

Thanx for pointing that out

My mistake for not pointing out that XP was not fully supported subsequent to the 5730 update. 

I can see how that is misleading… I will update the release notes.

NB: Version 5835 was made the base version and a note applied:
Applies to Windows 7, 8 and 10

Regards
