### ISSUE TITLE
Windows PE support

### ISSUE THREAD

**Issue by nsy16** [Superfly-Inc/ShowKeyPlus#16]
ShowKeyPlus1.0.6594 not executing under windows PE 64 bit environment created with Windows ADK for Windows 10, version 1709. Program can be seen momentarily in taskmgr then disappears.

**Comment by Superfly-Inc** [comment]
I will be uploading an x64 version later. It will form part of the same zip file that has the current (MSIL) version.

I will report back here when done.

Thanx for your feedback.

**Comment by Superfly-Inc** [comment]
Updated latest release with 64-bit version. Please download the updated zip file.
