### ISSUE TITLE
Outbond comunication

### ISSUE THREAD

**Issue by vaoff** [Superfly-Inc/ShowKeyPlus#17]
Hi when I use the program I see on firewall attempt to outbound comunication on port 443. May i ask for what porpose? Also i dont see source code to download just packed readme files as source code.

**Comment by Superfly-Inc** [comment]
Hi @vaoff 
This issue has been covered here:
https://github.com/Superfly-Inc/ShowKeyPlus/issues/7

Shoud you not wish to have the version check, you can use th UWP pre-release version which has that code stripped.

Thanx for your feedback.
