### ISSUE TITLE
Where is the source ?

### ISSUE THREAD

**Issue by joecare99** [Superfly-Inc/ShowKeyPlus#20]
Source still missing, licence still GPL!

**Comment by Superfly-Inc** [comment]
Hi 
I did not publish the source as this is not a collaborative project.

The GPL 2 states "...that you receive source code **or can get it if you want it,**  

To this end the code is not obfuscated and can be got with reflection.

Should this be in contradiction of GPL 2.0 I will change the licence.

Thanx for you input.
