### ISSUE TITLE
Windows 10 version 1903 - Original Windows 8 key not retrieved

### ISSUE THREAD

**Issue by geolives-contact** [Superfly-Inc/ShowKeyPlus#23]
Hello.

On the latest edition of Windows 10 (version 1903), for computers installed directly with Windows 8 keys in a clean install process, and which have been delivered a digital activation, the tool doesn't display the original Windows 8 key and edition (only the Windows 10 generic key is displayed).

Is it a known issue? Are you working on it? or is there a limitation in this version of Windows 10 which prevents from obtaining this information?

Thank you.

Best regards.

**Comment by Superfly-Inc** [comment]
Hi geolives

A clean install removes all traces of the original installaton and the key will not be there - only an upgrade will show the original key.

Regards
