### ISSUE TITLE
Mister

### ISSUE THREAD

**Issue by nicholas1935** [Superfly-Inc/ShowKeyPlus#25]
Launching ShowKeyPlus gave me Product Key:  QKMNQ-9T2.....  
Unfortunately, I got an error prompt that the number 2 is not acceptable in the product code.
Please note, I purchased the machine at the US Army West Point Post Exchange, at a Black Friday Door Buster  sale.   It was taken from a stack of all the same model.  So I don't believe it was a fraudulent machine.
Any help you can give me will be greatly appreciated.
Thank you,
Nick M.
njmx1@juno.com

**Comment by Superfly-Inc** [comment]
Hi Nick

Thanx for your feedback. 

The number 2 is perfectly acceptable - eg. my system has Microsoft's default key for Pro for Workstations with a 2 as part of that key.

![CaptureKey](https://user-images.githubusercontent.com/12848924/75101971-ecb2b900-55ec-11ea-9b09-2e7a6bcfdf86.PNG)

How did you get the message that it's not a valid key?

Cheers

**Comment by nicholas1935** [comment]
Hi - While inputting the key, trying to get Windows 10 Home installed, it stopped at the numeral 2, saying that it was not OK.  The key probably works fine for Pro, but my original version was Home. For background info: The computer I bought at the US Army Exchange Service, (I am a retired veteran and have Exchange privileges) came with Windows 10 Home installed.  I was infected by a virus.  I took the computer to Compucity in Newburgh, NY.  Their solution; copy the data, wipe the computer, and re-install a legit copy, but of Pro, which is the only copy of 10 they had.
 Except for a nag, "Activate Windows ,,,," in faint background, it worked fine, and even  accepted updates. The owner of the store was approached by a headhunter rep from a large Drug firm in Fishkill, NY, who made him an employment offer he couldn't refuse.  No recourse there. I  would like to get back to the original Windows 10, which two computer wizards claim is till in my computer.  Their advice, buy a new license.  At 85 years old, existing on a 1999 pension and my life savings, I would rather live with the nag. And therein is my problem. Thank you for taking the time from your busy day to help, but apparently, there is no help for this problem.  That's too bad, since the rumor is that Windows 11 will have a similar format to Windows 7, which many think is superior to the Windows 10 pictures format.  However, unless the US Army Exchange Service comes up with another Black Friday computer sale, I'll forgo the overpriced MS Windows 10program.  Kindly note, the HP Laptop computer cost me $150.00 with the Win 10 program.  Check out the price if a Win 10 program - obscene. Best regards,Nick M. 

---------- Original Message ----------

**Comment by Superfly-Inc** [comment]
Hello again 

You may want to explore your problem in more depth at the ShowKeyPlus discussion forum. 

https://www.tenforums.com/software-apps/2577-showkeyplus.html

There may be others that have encountered a similar problem, or we can explore in more depth yours in particular.

Regards
