### ISSUE TITLE
ShowKeyPlus 1.14.1 - Only English?

### ISSUE THREAD

**Issue by bovirus** [Superfly-Inc/ShowKeyPlus#29]
@Superfly-Inc 

I found on internet ShowKeyPlus 1.14.1.
But it's only English.
No italian version available.

**Comment by Superfly-Inc** [comment]
1.1.14.1 is the old .Net Framework version (not the .Net Core version you tested in the Preview ) so it does not have the multi-language code. 

It's just that I have had no luck getting volunteers to do other language translations - so not sure if the majority of users want this -  it seems we are going to be stuck with English and Italian for the time being. 

I will back-port Italian language into the next release.

**Comment by bovirus** [comment]
@Superfly-Inc 

Please take care that one translator for Italian language will be always there.
Thanks.
