### ISSUE TITLE
Активация OEM ключом

### ISSUE THREAD

**Issue by RomanIPDev** [Superfly-Inc/ShowKeyPlus#30]
Здравствуйте.
Добавьте пожалуйста в функционал ShowKeyPlus активацию OEM ключом. 
Это возможно при помощи стандартной команды changepk.exe /ProductKey %OEMKey%

**Comment by Superfly-Inc** [comment]
Hi 

Спасибо, но у меня есть отдельное приложение для активации. Я рассмотрю возможность добавления его туда.
