### ISSUE TITLE
Source code is missing

### ISSUE THREAD

**Issue by dyeske** [Superfly-Inc/ShowKeyPlus#32]
The source code package does not contain any sourcecode.

**Comment by Superfly-Inc** [comment]
It's not open source - is there any code in particular you are interested in?

**Comment by dyeske** [comment]
> It's not open source - is there any code in particular you are interested in?

I'm interested in being able to compile it myself just like every other project on github.  It's fraudulent to have a link to download the source code if it's not available.  Remove your licence for the source code and remove the links to download the source code or you might be violating the github TOS.  What are you trying to hide?

https://github.com/Superfly-Inc/ShowKeyPlus/releases/tag/ShowKeyPlus1.1.14.1

**Comment by gak1234** [comment]
Whatever, if anything, he is trying to hide... it isn't very rare or
special. The tool is easily decompiled and reversed, and most of the
payload is existing libraries.

**Comment by Superfly-Inc** [comment]
@dyeske  if I was trying to hide anything the code would be obfuscated - attempt your own app instead. I'm not familiar enough with the GitHub site to delete the links - took me long enough to get the MIT licence thing on.

@gak1234 Correct - this is not rocket science it's merely my take on existing shit that I broadened on like taking it to ,net core whatever. ProduKey and Magic JellyBean could have done the same. It's my project I'm sharing the results only.
