### ISSUE TITLE
Source code is not available

### ISSUE THREAD

**Issue by iakovmarkov** [Superfly-Inc/ShowKeyPlus#36]
Hello.
Older releases of this software were licensed under GNU GPL v2. According to GPL you should distribute source code alongside the binaries or respond to requests for source code.
Please, provide source code for those versions.

**Comment by Superfly-Inc** [comment]
Oh here we go again :roll-eyes:

Every version's TOC had the MIT licence - I don't care what GitHub slaps on the download page.

Complain to the GitHub police - I'll gladly move elsewhere if they want.

There are 3 types of dev's

1. The leeches that want the entire code verbatim - the spoon-feed me crowd.
2. The dev. student that has the insight to 'reflect/reverse' and figure what's what.
3. The intelligent dev. that can figure things out from merely a use scenario. 

Which of those are you?

**Comment by Tea23** [comment]
Ok but the GPL source code should be made available again.
