### ISSUE TITLE
Language translators required

### ISSUE THREAD

**Issue by Superfly-Inc** [Superfly-Inc/ShowKeyPlus#37]
I would like to include more languages - only English and Italian are included in the Preview thus far. 

If anyone is willing to provide translation from English to your own language let  me know please.

**Comment by olydiver2** [comment]
Hi, 

I can translate for French if you'd like me to.
Thanks.
Kind regards, Olivier

PS : thanks for developing this product, I use it and I find it perfect !

**Comment by Superfly-Inc** [comment]
merci beaucoup Olivier

Please see https://github.com/Superfly-Inc/ShowKeyPlus/issues/27 how we did the Italian translation 

@bovirus will you help if @olydiver2 gets stuck?

Thanx guys :)

**Comment by bovirus** [comment]
@Superfly-Inc 

Of course I will happy to provide my contruibution.

**Comment by Superfly-Inc** [comment]
@bovirus 

I knew I could count on you - hope you are doing well on your side of the world .. 
Just something I think we can tweak ... when I run Italian it's fine but the SaveAs still has Text **file**, Word **Document** , Excel **Document** etc - should we not translate that too?

**Comment by bovirus** [comment]
Quite well on my side. I hope the same for you,

I did the job so many times ago that I'm not sure.
Can I have a list of strings to check?

**Comment by Superfly-Inc** [comment]
@bovirus

Here you go - added the following:

Excel Document	
marker	
Text File	
Word Document	

[ShowKeyPlus.it.xlf.zip](https://github.com/Superfly-Inc/ShowKeyPlus/files/6308205/ShowKeyPlus.it.xlf.zip)

@olydiver2

Here is the file that still needs the French input. 

PS updated with some translations
[ShowKeyPlus.fr.zip](https://github.com/Superfly-Inc/ShowKeyPlus/files/6309384/ShowKeyPlus.fr.zip)

**Comment by Superfly-Inc** [comment]
I decided to batch translate - see the new preview for languages - needs to be checked 

Used Google but their bots blocked me pretty quickly from with translation requests.

**Comment by bovirus** [comment]
@Superfly-Inc 

Italian language update

[ShowKeyPlus.it.xlf.zip](https://github.com/Superfly-Inc/ShowKeyPlus/files/6330954/ShowKeyPlus.it.xlf.zip)

Could you pelase explain the meaning of "state=" in language file?

What are trhe differences between "translated"/"final"/"new" state?

**Comment by Superfly-Inc** [comment]
Thanx @bovirus 

I'm not sure - I assume it's just for the translators to keep track of each translation - particularly if it's done in a group. The xlf does not populate that into the various resource.resx  files (which is what the app uses).
Only the Resource ID and it's associated translated string gets pulled through.

**Comment by Superfly-Inc** [comment]
RC (non-Core version) preview now available with built-in languages.

**Comment by bovirus** [comment]
@Superfly-Inc 

Where (link) can I get this RC version?

**Comment by Superfly-Inc** [comment]
@bovirus 

It's under https://github.com/Superfly-Inc/ShowKeyPlus/releases/tag/ShowKeyPlusWPF

I added some more translations for the exceptions like this one

![image](https://user-images.githubusercontent.com/12848924/119223337-211b6a80-baf9-11eb-80ba-131beb1369a9.png)

**Comment by bovirus** [comment]
@Superfly-Inc 

Some issues about translation

![image](https://user-images.githubusercontent.com/1262554/119231296-6e5f0280-bb20-11eb-854d-2c267a62f4ec.png)

![image](https://user-images.githubusercontent.com/1262554/119231254-3bb50a00-bb20-11eb-8191-f3a9ce8bf8dd.png)

![image](https://user-images.githubusercontent.com/1262554/119231265-45d70880-bb20-11eb-8b37-eb269e15bb66.png)

For me default file name for save key file and Restroe key fiel should be the same. 

For me Save key fiel name is OK.
It should by default teh same also for recoevr key file.

I propose you to increase window height to have some space below "About" option on the left

**Comment by Superfly-Inc** [comment]
Thanx @bovirus 

I will work on these changes pronto

**Comment by Superfly-Inc** [comment]
@bovirus

I have implemented the changes you require - please check v 1.1.14.6 

Also I'd like you to check the tool tips as well (navigation menu items and product keys)

PS the Recovery file is a Windows file - thus the name ("SOFTWARE") - I can't change that.

**Comment by bovirus** [comment]
@Superfly-Inc 

Thanks for the changes.

I propose you to use slighty diffrently the menu layout on the left.

Origin of left menu option (Home) upper
Left space bewteen ecah line of option on the left
Same space (line space) between each option on the left

 like in this screnshot.

![image](https://user-images.githubusercontent.com/1262554/119237063-4204af80-bb3b-11eb-9066-e616d2052b56.png)

**Comment by Superfly-Inc** [comment]
@bovirus 

OK I'll work on the spacing - so Home double vertical space and the rest single space? - the classic is to have "Settings" right at the bottom (which in this instance will be About) as it's not part of the functionality and therefore not grouped. I will try different layouts and let you know.

BTW the  "Edizione OEM" in your screenshot is not supposed to be there when there is no OEM key - I have fixed that and uploaded (same version number) so just replace your current 1.1.14.6 with the new one.

**Comment by bovirus** [comment]
I beleieve that you choose the option order that you like (Home as first) but I prefer to have all options with same vertical space (interline)

As in my layout put all options in left panel from top to boottm and leave space after last option.

**Comment by ViBE-HU** [comment]
Sorry for necroing, but if I can still participate I would like to ask for the strings and would do a translation too.
