### ISSUE TITLE
.Net FrameWork Depedency

### ISSUE THREAD

**Issue by spinalgr1990** [Superfly-Inc/ShowKeyPlus#40]
Is it possible to remove the .Net FrameWork Depedency ?

my pc supports only .Net FrameWork  version 4.6.2   :(

**Comment by Superfly-Inc** [comment]
No problem I can target 4.6.1 as minimum - lower than that will mean some NuGet components won't work. The next desktop release is due soon if I get no crashes etc from the Store. UWP version is on 1.1.16.0 already.  

I was not aware of hardware constraints on certain Framework versions... 

What do you think about everybody being on .Net Core instead?

Personally I wish MS just puts the Framework to bed and distributes .Net Core as a Windows update - so we can concentrate on .Net Core based apps instead.

Surely that will take care of any hardware issues as it is Linux compatible which typically runs on lower spec machines?

**Comment by spinalgr1990** [comment]
ok .Net Framework 4.6.1 will work on much more computers systems !

**Comment by Superfly-Inc** [comment]
@spinalgr1990 

Version 1.1.16.0 now set to minimum Framework 4.6.1 - please check and let me know if you have issues running it

Thanx

**Comment by spinalgr1990** [comment]
Yes working well now on my pc with net 4.6.1 !
Which is the difference between installed and original key ?


It will be great if you create a similar application for microsoft office

**Comment by Superfly-Inc** [comment]
Excellent.  The original key is the one that was installed before an upgrade. 

In  the below example Windows 7 was upgraded to Windows 10 - therefore the original key is the Windows 7 one 

![image](https://user-images.githubusercontent.com/12848924/121823994-2eb3b280-cca9-11eb-91c4-6203402a76e8.png)

Since MS Office 2013 the  keys are not easily obtainable - only the default keys are available - when I figure out how to get the full installed key I will add it.

**Comment by spinalgr1990** [comment]
some ideas for feed for MS Office :

It is not possible to view the complete key, only the last 5 characters like -6MWKP  and compare that to the list (if you have kept one) of the keys that were used.

In a command prompt type the following ;
 
cscript "C:\Program Files (x86)\Microsoft Office\Office16\OSPP.VBS" /dstatus or:
cscript "C:\Program Files\Microsoft Office\Office16\OSPP.VBS" /dstatus

Also 

for Office 2013 is ....\Office15\.... 
for Office 2010 is ....\Office14\.... 
 
Apparently MS no longer stores the full Product Key for Office 2013 and above in the registry.  Instead it stores a 1-way hash calculated from the PK, and since you can't reverse a hash you can't get the key back.  The hash is unique, and it's called ProductID, but there is no way to tie a PK to a PID

**Comment by Superfly-Inc** [comment]
> some ideas for feed for MS Office :
> 
> It is not possible to view the complete key, only the last 5 characters like -6MWKP and compare that to the list (if you have kept one) of the keys that were used.
> 
> In a command prompt type the following ;
> 
> cscript "C:\Program Files (x86)\Microsoft Office\Office16\OSPP.VBS" /dstatus or:
> cscript "C:\Program Files\Microsoft Office\Office16\OSPP.VBS" /dstatus
> 
> Also
> 
> for Office 2013 is ....\Office15....
> for Office 2010 is ....\Office14....
> 
> Apparently MS no longer stores the full Product Key for Office 2013 and above in the registry. Instead it stores a 1-way hash calculated from the PK, and since you can't reverse a hash you can't get the key back. The hash is unique, and it's called ProductID, but there is no way to tie a PK to a PID

Yes thanx, I am aware of the hash - I just meant I have not actually tried to reverse/decode it myself.
