### ISSUE TITLE
does not work on Microsoft Office

### ISSUE THREAD

**Issue by kolet** [Superfly-Inc/ShowKeyPlus#41]
hi there ,

i'v tried many licences keys for microsoft office 2019 pro , however  when checking the keys with showkeyplus it yield no result.

any reason why ?
can it be fixed?
is there a different source / software or manual commands that i can use to query microsoft servers to know what kind of license is that ?

thanks alot !

@Superfly-Inc 

for example  (hopefully people wont use the key maliciously ) 

![image](https://user-images.githubusercontent.com/17353839/126647354-c892834e-3dc9-4620-a405-30d9f15c48ab.png)

**Comment by Superfly-Inc** [comment]
Good idea ;) 

I will include it in the next Preview due out this weekend.

A quick test with a MAK key:
`Key Status		: Valid
Product Description	: Office15_ProjectProVL_MAK
Edition ID		: ProjectProVolume
Product Key Channel	: Volume:MAK
Eula Type		: ltMAK
MAK Count		: 2500`

**Comment by Superfly-Inc** [comment]
@kolet

Try the new Preview 
https://github.com/Superfly-Inc/ShowKeyPlus/releases/tag/ShowKeyPlusWPF

**Comment by Superfly-Inc** [comment]
No response - closed.
