### ISSUE TITLE
Minor german localization issues

### ISSUE THREAD

**Issue by SteLei1973** [Superfly-Inc/ShowKeyPlus#43]
Hi there, first of all, thanks for this great tool :)

I found two minor flaws in the german translation, which you might want to fix:

1.) On the left hand side (the menu), the second option in german reads "Überprüfen edition". A better translation would be "Edition überprüfen".
2.) When being on the startpage, on the right hand side the product information is shown. If no OEM-key was found in the firmware, the last entry reads currently in german: "OEM-Schlüssel in Firmwar nicht vorhandene". This could be fixed to "OEM-Schlüssel in Firmware nicht vorhanden"

Thanks again for your effort and best regards!

**Comment by Superfly-Inc** [comment]
Hi SteLei

Thanx ;) 

I had an issue posted requesting translations but got little response so I just did my own thing LOL 

I will definitely make the changes with the next release... still hoping we get Win 11 keys before then... 

Cheers
