### ISSUE TITLE
Display of Office-Keys?

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [Superfly-Inc/ShowKeyPlus#44]
Hi
should it also display keys from MS Office?

**Comment by Superfly-Inc** [comment]
Hi Pierre

Office keys are treated like MAK keys since O2013 - so not accessible - even slmgr uses the partial product key only - so no, keys for Office 2013 and later are not available - Belarc, ProduKey and others, reports the default/generic key only which is useless.

Cheers
