### ISSUE TITLE
Odd Microsoft usage

### ISSUE THREAD

**Issue by wyattwc** [Superfly-Inc/ShowKeyPlus#49]
Hello! 

While this isn't an issue per-say, I wanted to let you know Microsoft engineers that are working on licensing issues seem to be opting to install your software right away (no asking for consent, just going for it).

Wanted to let you know since you work hard on this tool, and Microsoft is using it to troubleshoot paying business customers (and probably not cutting you in)

**Comment by DasGerippe** [comment]
Looks like the license of this software permits the described usage.
See https://github.com/Superfly-Inc/ShowKeyPlus/blob/master/LICENSE
