### ISSUE TITLE
Doen't seem to detect Original Key and Edition on all PCs

### ISSUE THREAD

**Issue by SumatraPeter** [Superfly-Inc/ShowKeyPlus#6]
On a Dell desktop that had Windows 7 on it and now runs Windows 10 1511, ShowKeyPlus says _OEM Key: Windows 7 OEM marker present in firmware_ and correctly shows me the _Original Key_ and _Original Edition_.

However on an Acer laptop that also had Windows 7 on it and now runs Windows 10 1607, ShowKeyPlus says _OEM Key: Windows 7 OEM marker present in firmware_ but does **not** show me either the _Original Key_ or the _Original Edition_.

Why is this? Is it because the desktop was upgraded from Windows 7 to 10 (using the 1511 ISO), but the laptop was formatted and had Windows 10 clean installed on it (also using the 1511 ISO but then updated to 1607 via Windows Update)?

**Comment by Superfly-Inc** [comment]
Yes, that is correct. A clean install erases all traces of the original key. An upgrade stores the previous key in the new registry as well as retaining it in the old (Windows.old)

Thanx, I appreciate your feedback.
Cheers.

**Comment by SumatraPeter** [comment]
Thanks for the explanation. So since Windows 8 onwards there are no more stickers with keys on them and the keys are stored in the BIOS, does that mean that even with a clean install of Windows 10 on a Windows 8/8.1 system ShowKeyPlus will be able to successfully display the _Original Key_ and _Original Edition_?

**Comment by Superfly-Inc** [comment]
Kindof... The Win 8 OEM key will be the 'original' key and it's edition will be displayed there... in ShowKeyPlus land, original means previously installed.

We have seen downgraded Win 8 to Win 7 PC's still having the Win 8 OEM key in the firmware.... so in a way that was the original key...

**Comment by SumatraPeter** [comment]
Got it. Closing this issue now but will continue to monitor the other one I opened. Thanks.
