### ISSUE TITLE
Check product key from file ?

### ISSUE THREAD

**Issue by DraGula** [Superfly-Inc/ShowKeyPlus#8]
HI,
Is there any commandline options for ShowKeyPlus ? 
I would like to check a lot of windows product key from a file, and of course generate an output file with the result.
Is there any way to do that ? Maybe an evolution ?
Thanks!

**Comment by Superfly-Inc** [comment]
Hi DraGula

Yes there is:
Use CLI to generate a text file of installed, original and OEM key(s) and their editions, silently.
Usage:
"[path]ShowKeyPlus.exe"  "[path][filename].txt" (or any text compatible extension, eg: .doc, .csv etc

You will have to put it in a script loop to iterate the keys in your file.

**Comment by Svoffer** [comment]
How do you get the product information via the key? 
I could really use this in a Powershell script for a report on the expenses on upgrading 2k+ machines to Win10.

**Comment by Superfly-Inc** [comment]
Depends on what you would like to display in your report...and which key/

**Comment by Svoffer** [comment]
I have a script that returns the OEM key, so I need to know what Windows product it is for.
E.g. Windows 8 or Windows 10.
I have played around with VAMT, but it is a little cumbersome to have all machines return the key and then import them to VAMT and the retrieve the product.
If I could check the key directly in Powershell it would greatly decrease the amount for work I need to do.

This way I would incorporate it into our OS deployment for future upgrade cost estimates.
I already have a database containing hardware information and first install date, so we can be proactive when machines are getting outdated.

**Comment by MPR-Git** [comment]
Exactly the same question a "few years later" for the same needs 🙄
